import { createAction, handleActions } from 'redux-actions';
import * as api from 'lib/api';

import { Map, fromJS } from 'immutable';
import { pender } from 'redux-pender';


import _ from 'lodash';
import { List } from 'immutable';
import { stat } from 'fs';
//action types
const TOUR_DB = 'map/TOUR_DB'
const NAVER_MAP = 'map/NAVER_MAP'
const SELECT_COURSE = 'map/SELECT_COURSE'
const SELECT_COURSE_CLOSE = 'map/SELECT_COURSE_CLOSE'
const SELECT_BASKET_LIST = 'map/SELECT_BASKET_LIST'
//action creators
export const tourDB = createAction(TOUR_DB, api.tourDB)
export const naverMap = createAction(NAVER_MAP)
export const selectCourse = createAction(SELECT_COURSE)
export const closeCourse = createAction(SELECT_COURSE_CLOSE)
export const selectBasket = createAction(SELECT_BASKET_LIST)


//initial state
let initialState = fromJS({
    mapData: [
        { zoom: 7, center: new window.naver.maps.LatLng(37.5666805, 126.9784147), selected: false }
    ],
    courseData: [
        {
            center: new window.naver.maps.LatLng(37.5666805, 126.9784147),
            lat: null,
            lng: null,
            selected: false,
            title: 'test1',
            intro: null,
            text: '내용1',
            image: 'https://source.unsplash.com/60x60/?watermelon',
            courseSelected: false,
            addr: null,
            close: null,
            open: null,
            price: null,
            sale: null,
            tel1: null,
            tel2: null,
            bus: null,
            train: null,
            web: null,

        },
        {
            center: new window.naver.maps.LatLng(37.5666805, 126.9784147),
            lat: null,
            lng: null,
            selected: false,
            title: 'test1',
            intro: null,
            text: '내용1',
            image: 'https://source.unsplash.com/60x60/?watermelon',
            courseSelected: false,
            addr: null,
            close: null,
            open: null,
            price: null,
            sale: null,
            tel1: null,
            tel2: null,
            bus: null,
            train: null,
            web: null,
        },
        {
            center: new window.naver.maps.LatLng(37.5666805, 126.9784147),
            lat: null,
            lng: null,
            selected: false,
            title: 'test1',
            intro: null,
            text: '내용1',
            image: 'https://source.unsplash.com/60x60/?watermelon',
            courseSelected: false,
            addr: null,
            close: null,
            open: null,
            price: null,
            sale: null,
            tel1: null,
            tel2: null,
            bus: null,
            train: null,
            web: null,
        },
        {
            center: new window.naver.maps.LatLng(37.5666805, 126.9784147),
            lat: null,
            lng: null,
            selected: false,
            title: 'test1',
            intro: null,
            text: '내용1',
            image: 'https://source.unsplash.com/60x60/?watermelon',
            courseSelected: false,
            addr: null,
            close: null,
            open: null,
            price: null,
            sale: null,
            tel1: null,
            tel2: null,
            bus: null,
            train: null,
            web: null,
        }
    ],
    test: [
        {
            Course_selected: null,
            Event_cd: null,
            Kind_cd: null,
            Region_cd: null,
            Selected: null,
            Tour_addr: null,
            Tour_cd: null,
            Tour_close: null,
            Tour_gps_lat: null,
            Tour_gps_lon: null,
            Tour_img: null,
            Tour_intro: null,
            Tour_nm: null,
            Tour_open: null,
            Tour_pic: null,
            Tour_price: null,
            Tour_sale: null,
            Tour_tel1: null,
            Tour_tel2: null,
            Tour_traffic_bus: null,
            Tour_traffic_train: null
        },
        {
            Course_selected: null,
            Event_cd: null,
            Kind_cd: null,
            Region_cd: null,
            Selected: null,
            Tour_addr: null,
            Tour_cd: null,
            Tour_close: null,
            Tour_gps_lat: null,
            Tour_gps_lon: null,
            Tour_img: null,
            Tour_intro: null,
            Tour_nm: null,
            Tour_open: null,
            Tour_pic: null,
            Tour_price: null,
            Tour_sale: null,
            Tour_tel1: null,
            Tour_tel2: null,
            Tour_traffic_bus: null,
            Tour_traffic_train: null
        },
        {
            Course_selected: null,
            Event_cd: null,
            Kind_cd: null,
            Region_cd: null,
            Selected: null,
            Tour_addr: null,
            Tour_cd: null,
            Tour_close: null,
            Tour_gps_lat: null,
            Tour_gps_lon: null,
            Tour_img: null,
            Tour_intro: null,
            Tour_nm: null,
            Tour_open: null,
            Tour_pic: null,
            Tour_price: null,
            Tour_sale: null,
            Tour_tel1: null,
            Tour_tel2: null,
            Tour_traffic_bus: null,
            Tour_traffic_train: null
        },
        {
            Course_selected: null,
            Event_cd: null,
            Kind_cd: null,
            Region_cd: null,
            Selected: null,
            Tour_addr: null,
            Tour_cd: null,
            Tour_close: null,
            Tour_gps_lat: null,
            Tour_gps_lon: null,
            Tour_img: null,
            Tour_intro: null,
            Tour_nm: null,
            Tour_open: null,
            Tour_pic: null,
            Tour_price: null,
            Tour_sale: null,
            Tour_tel1: null,
            Tour_tel2: null,
            Tour_traffic_bus: null,
            Tour_traffic_train: null
        },
        {
            Course_selected: null,
            Event_cd: null,
            Kind_cd: null,
            Region_cd: null,
            Selected: null,
            Tour_addr: null,
            Tour_cd: null,
            Tour_close: null,
            Tour_gps_lat: null,
            Tour_gps_lon: null,
            Tour_img: null,
            Tour_intro: null,
            Tour_nm: null,
            Tour_open: null,
            Tour_pic: null,
            Tour_price: null,
            Tour_sale: null,
            Tour_tel1: null,
            Tour_tel2: null,
            Tour_traffic_bus: null,
            Tour_traffic_train: null
        },
        {
            Course_selected: null,
            Event_cd: null,
            Kind_cd: null,
            Region_cd: null,
            Selected: null,
            Tour_addr: null,
            Tour_cd: null,
            Tour_close: null,
            Tour_gps_lat: null,
            Tour_gps_lon: null,
            Tour_img: null,
            Tour_intro: null,
            Tour_nm: null,
            Tour_open: null,
            Tour_pic: null,
            Tour_price: null,
            Tour_sale: null,
            Tour_tel1: null,
            Tour_tel2: null,
            Tour_traffic_bus: null,
            Tour_traffic_train: null
        },
        {
            Course_selected: null,
            Event_cd: null,
            Kind_cd: null,
            Region_cd: null,
            Selected: null,
            Tour_addr: null,
            Tour_cd: null,
            Tour_close: null,
            Tour_gps_lat: null,
            Tour_gps_lon: null,
            Tour_img: null,
            Tour_intro: null,
            Tour_nm: null,
            Tour_open: null,
            Tour_pic: null,
            Tour_price: null,
            Tour_sale: null,
            Tour_tel1: null,
            Tour_tel2: null,
            Tour_traffic_bus: null,
            Tour_traffic_train: null
        },
        {
            Course_selected: null,
            Event_cd: null,
            Kind_cd: null,
            Region_cd: null,
            Selected: null,
            Tour_addr: null,
            Tour_cd: null,
            Tour_close: null,
            Tour_gps_lat: null,
            Tour_gps_lon: null,
            Tour_img: null,
            Tour_intro: null,
            Tour_nm: null,
            Tour_open: null,
            Tour_pic: null,
            Tour_price: null,
            Tour_sale: null,
            Tour_tel1: null,
            Tour_tel2: null,
            Tour_traffic_bus: null,
            Tour_traffic_train: null
        },
        {
            Course_selected: null,
            Event_cd: null,
            Kind_cd: null,
            Region_cd: null,
            Selected: null,
            Tour_addr: null,
            Tour_cd: null,
            Tour_close: null,
            Tour_gps_lat: null,
            Tour_gps_lon: null,
            Tour_img: null,
            Tour_intro: null,
            Tour_nm: null,
            Tour_open: null,
            Tour_pic: null,
            Tour_price: null,
            Tour_sale: null,
            Tour_tel1: null,
            Tour_tel2: null,
            Tour_traffic_bus: null,
            Tour_traffic_train: null
        },
        {
            Course_selected: null,
            Event_cd: null,
            Kind_cd: null,
            Region_cd: null,
            Selected: null,
            Tour_addr: null,
            Tour_cd: null,
            Tour_close: null,
            Tour_gps_lat: null,
            Tour_gps_lon: null,
            Tour_img: null,
            Tour_intro: null,
            Tour_nm: null,
            Tour_open: null,
            Tour_pic: null,
            Tour_price: null,
            Tour_sale: null,
            Tour_tel1: null,
            Tour_tel2: null,
            Tour_traffic_bus: null,
            Tour_traffic_train: null
        },
        {
            Course_selected: null,
            Event_cd: null,
            Kind_cd: null,
            Region_cd: null,
            Selected: null,
            Tour_addr: null,
            Tour_cd: null,
            Tour_close: null,
            Tour_gps_lat: null,
            Tour_gps_lon: null,
            Tour_img: null,
            Tour_intro: null,
            Tour_nm: null,
            Tour_open: null,
            Tour_pic: null,
            Tour_price: null,
            Tour_sale: null,
            Tour_tel1: null,
            Tour_tel2: null,
            Tour_traffic_bus: null,
            Tour_traffic_train: null
        },
        {
            Course_selected: null,
            Event_cd: null,
            Kind_cd: null,
            Region_cd: null,
            Selected: null,
            Tour_addr: null,
            Tour_cd: null,
            Tour_close: null,
            Tour_gps_lat: null,
            Tour_gps_lon: null,
            Tour_img: null,
            Tour_intro: null,
            Tour_nm: null,
            Tour_open: null,
            Tour_pic: null,
            Tour_price: null,
            Tour_sale: null,
            Tour_tel1: null,
            Tour_tel2: null,
            Tour_traffic_bus: null,
            Tour_traffic_train: null
        },
        {
            Course_selected: null,
            Event_cd: null,
            Kind_cd: null,
            Region_cd: null,
            Selected: null,
            Tour_addr: null,
            Tour_cd: null,
            Tour_close: null,
            Tour_gps_lat: null,
            Tour_gps_lon: null,
            Tour_img: null,
            Tour_intro: null,
            Tour_nm: null,
            Tour_open: null,
            Tour_pic: null,
            Tour_price: null,
            Tour_sale: null,
            Tour_tel1: null,
            Tour_tel2: null,
            Tour_traffic_bus: null,
            Tour_traffic_train: null
        },
        {
            Course_selected: null,
            Event_cd: null,
            Kind_cd: null,
            Region_cd: null,
            Selected: null,
            Tour_addr: null,
            Tour_cd: null,
            Tour_close: null,
            Tour_gps_lat: null,
            Tour_gps_lon: null,
            Tour_img: null,
            Tour_intro: null,
            Tour_nm: null,
            Tour_open: null,
            Tour_pic: null,
            Tour_price: null,
            Tour_sale: null,
            Tour_tel1: null,
            Tour_tel2: null,
            Tour_traffic_bus: null,
            Tour_traffic_train: null
        },
        {
            Course_selected: null,
            Event_cd: null,
            Kind_cd: null,
            Region_cd: null,
            Selected: null,
            Tour_addr: null,
            Tour_cd: null,
            Tour_close: null,
            Tour_gps_lat: null,
            Tour_gps_lon: null,
            Tour_img: null,
            Tour_intro: null,
            Tour_nm: null,
            Tour_open: null,
            Tour_pic: null,
            Tour_price: null,
            Tour_sale: null,
            Tour_tel1: null,
            Tour_tel2: null,
            Tour_traffic_bus: null,
            Tour_traffic_train: null
        },
    ]
});
//reducer
export default handleActions({
    ...pender({
        type: TOUR_DB,
        onSuccess: (state, action) => {
            const { data } = action.payload;

            state.getIn(['test']).toJS().map((a,index)=>{
                state = state.mergeIn(['test', index], 
                {
                    Course_selected: false,
                    Event_cd: data[index].Event_cd,
                    Kind_cd: data[index].Kind_cd,
                    Region_cd: data[index].Region_cd,
                    Selected: data[index].Selected,
                    Tour_addr: data[index].Tour_addr,
                    Tour_cd: data[index].Tour_cd,
                    Tour_close: data[index].Tour_close,
                    Tour_gps_lat: data[index].Tour_gps_lat,
                    Tour_gps_lon: data[index].Tour_gps_lon,
                    Tour_img: data[index].Tour_img,
                    Tour_intro: data[index].Tour_intro,
                    Tour_nm: data[index].Tour_nm,
                    Tour_open: data[index].Tour_open,
                    Tour_pic: data[index].Tour_pic,
                    Tour_price: data[index].Tour_price,
                    Tour_sale: data[index].Tour_sale,
                    Tour_tel1: data[index].Tour_tel1,
                    Tour_tel2: data[index].Tour_tel2,
                    Tour_traffic_bus: data[index].Tour_traffic_bus,
                    Tour_traffic_train: data[index].Tour_traffic_train    
                })
            })
            return state
        }
    }),
    [SELECT_COURSE]: (state, action) => {
        const { index } = action.payload;
        return state.setIn(['test', index, 'Selected'], !state.getIn(['test', index, 'Selected']))
    },
    [SELECT_COURSE_CLOSE]: (state, action) => {
        const { index } = action.payload;
        console.log(index)
        // return state.setIn(['coursData', i, 'selected'], bool)
        return state.setIn(['courseData', index, 'selected'], !state.getIn(['courseData', index, 'selected']))
    },
    [SELECT_BASKET_LIST]: (state, action) => {
        const { selected, index, bool, i } = action.payload;
        console.log('bool', bool)
        console.log('selected', selected)
        return state.setIn(['test', i, 'Course_selected'], bool)
        // return state.setIn(['test', index, 'Course_selected'], !state.getIn(['test', index, 'Course_selected']))
    },
}, initialState)